In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [18]:
samplesub_df = pd.read_csv("C:/diabetes-classification-challenge/Dataset/allzeroes_sample.csv")

In [19]:
print(samplesub_df.columns)

Index(['Outcome'], dtype='object')


In [20]:
outcome = []
outcome.append("Outcome")

In [21]:
dfx = pd.read_csv("C:/diabetes-classification-challenge/Dataset/TrainingData/Diabetes_XTrain.csv")
dfx.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [22]:
dfy = pd.read_csv("C:/diabetes-classification-challenge/Dataset/TrainingData/Diabetes_YTrain.csv")

In [23]:
print(dfx.shape)
dfx.values

(576, 8)


array([[  7.   , 168.   ,  88.   , ...,  38.2  ,   0.787,  40.   ],
       [  8.   , 110.   ,  76.   , ...,  27.8  ,   0.237,  58.   ],
       [  7.   , 147.   ,  76.   , ...,  39.4  ,   0.257,  43.   ],
       ...,
       [  2.   , 122.   ,  60.   , ...,  29.8  ,   0.717,  22.   ],
       [  4.   , 154.   ,  72.   , ...,  31.3  ,   0.338,  37.   ],
       [  1.   ,  88.   ,  78.   , ...,  32.   ,   0.365,  29.   ]])

In [24]:
print(dfy.shape)
dfy.values

(576, 1)


array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
    

In [25]:
X_train = dfx.values

In [26]:
Y_train = dfy.values

In [27]:
test_df = pd.read_csv("C:/diabetes-classification-challenge/Dataset/TestData/Diabetes_Xtest.csv")

In [28]:
X_test = test_df.values

In [29]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))
nearestpoints = 17
def knn(X,Y,test,k=nearestpoints):
    vals = []
    m = X.shape[0]
    
    for i in range(m):
        d = dist(test,X[i])
        vals.append((d,Y[i]))
        
    vals = sorted(vals)
    vals = vals[:k]
    vals = np.array(vals)
    
    new_vals = np.unique(vals[:,1],return_counts=True)
    index = new_vals[1].argmax()
    pred = new_vals[0][index]
    return(pred)

In [30]:
for i in range(X_test.shape[0]):
    pred = knn(X_train,Y_train,X_test[i])
    outcome.append(int(pred))

In [31]:
outcome = np.asarray(outcome)
df = pd.DataFrame(outcome)

In [33]:
df.to_csv("C:/diabetes-classification-challenge/submission17"+str(nearestpoints)+".csv",index=False,header=0)

In [35]:
df = pd.read_csv("C:/diabetes-classification-challenge/submission17.csv")
df.shape

(192, 1)

In [36]:
df.values

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [37]:
df.columns

Index(['Outcome'], dtype='object')